name: kms
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  tdesign_flutter: ^0.1.0
  http: ^1.2.2
  colored_json: ^1.1.2
  sidebarx: ^0.17.1
  provider: ^6.1.2
  get: ^4.6.6
  get_storage: ^2.1.1
  pluto_grid: ^8.0.0
  draggable_home: ^1.0.2
  better_player: ^0.0.84
  path_provider: ^2.1.5
  file_picker: ^8.1.3
  persistent_bottom_nav_bar: ^6.2.1
  animated_bottom_navigation_bar: ^1.3.3
  flutter_highlight: ^0.7.0
  highlighting: ^0.9.0+11.8.0
  google_fonts: ^6.2.1
  multi_split_view: ^3.6.0
  expandable: ^5.0.1
  url_launcher: ^6.3.1
  easy_image_viewer: ^1.5.1
  uuid: ^4.5.1
  flutter_joystick: ^0.2.1
  scrollable_positioned_list: ^0.3.8
  appflowy_editor: ^4.0.0
  pluto_layout: ^1.0.0
  ulid: ^2.0.1
  tabbed_view: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flex_color_scheme: ^8.0.0-dev.2
  test: ^1.25.7

flutter:
  uses-material-design: true
  assets:
      - assets/
  fonts:
    - family: HarmonyOS Sans Regular
      fonts:
        - asset: assets/fonts/HarmonyOS_Sans_Regular.ttf