name: kms
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  tdesign_flutter: ^0.1.0
  http: ^1.2.2
  colored_json: ^1.1.2
  sidebarx: ^0.17.1
  provider: ^6.1.2
  get: ^4.6.6
  get_storage: ^2.1.1
  pluto_grid: ^8.0.0
  draggable_home: ^1.0.2
  better_player: ^0.0.84
  path_provider: ^2.1.5
  file_picker: ^8.1.3
  flutter_quill: ^10.8.5
  persistent_bottom_nav_bar: ^6.2.1
  animated_bottom_navigation_bar: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flex_color_scheme: ^8.0.0-dev.2

flutter:
  uses-material-design: true
  assets:
      - assets/
